remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme  
kramdown:
  input: GFM
  math_engine: mathjax 
title: VUB Algebra Research Group
description: Skew braces and the YBE
show_downloads: false
is_project_page: false
