remote_theme: pages-themes/modernist@v0.2.0
markdown: kramdown
kramdown:
  math_engine: mathjax
plugins:
- jekyll-remote-theme  
- jekyll-spaceship
plugins:
title: VUB Algebra Research Group
description: Skew braces and the YBE
show_downloads: false
is_project_page: false
